# Week 12

**A complete Data Science project**

**I choose a start-up business problem.**

where early startup which as SaaS or a fintech app, doesn't having any historical data about frauds, like if that startup offers any subscriptions, fraudsters may use stolen credit cards(payment fraud), or if the company offers a promo code fraudster may create thouands of fake accounts to drain those promo codes.

**My objective is to flag such a payment frauds accounts without harming the legit user and also ensuring the company's captial won't slip into hands of fraudsters.**

*the dataset as decided.. the **PaySim Synthetic Dataset(from kaggle)***

In [6]:
import pandas as pd

df = pd.read_csv('data/paysim_sample.csv')

print(df.shape)

df.head()

(318131, 11)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,10,CASH_IN,367088.24,C291409265,1328.10,368416.34,C1132709076,2312937.66,3837053.94,0,0
1,10,PAYMENT,27004.49,C535489359,0.00,0.00,M2110652315,0.00,0.00,0,0
2,8,PAYMENT,2173.75,C927615422,820.00,0.00,M1658216730,0.00,0.00,0,0
3,10,TRANSFER,19670.92,C1562020231,5416.73,0.00,C2060926688,63327.50,0.00,0,0
4,10,PAYMENT,17394.26,C1165434512,168543.14,151148.88,M490546299,0.00,0.00,0,0

In [4]:
df[df['isFraud']==1]

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
500,9,TRANSFER,2539898.07,C394488466,2539898.07,0.0,C575638324,0.00,261290.69,1,0
1558,7,TRANSFER,21729.00,C1686905633,21729.00,0.0,C824421402,0.00,0.00,1,0
3555,3,TRANSFER,10539.37,C1134864869,10539.37,0.0,C118648358,0.00,0.00,1,0
3600,1,CASH_OUT,25071.46,C1275464847,25071.46,0.0,C1364913072,9083.76,34155.22,1,0
5728,10,TRANSFER,2662734.59,C1182702586,2662734.59,0.0,C2143409210,0.00,0.00,1,0
...,...,...,...,...,...,...,...,...,...,...,...
317731,732,CASH_OUT,249365.63,C1261928380,249365.63,0.0,C1342636720,0.00,249365.63,1,0
317742,694,CASH_OUT,10000000.00,C611266537,10000000.00,0.0,C305170140,0.00,10000000.00,1,0
317824,695,TRANSFER,665676.43,C53387577,665676.43,0.0,C1328394120,0.00,0.00,1,0
318069,694,CASH_OUT,186567.41,C245911074,186567.41,0.0,C370902983,0.00,186567.41,1,0
318071,716,TRANSFER,921393.95,C1878448827,921393.95,0.0,C765829328,0.00,0.00,1,0